apiVersion: apps/v1
kind: Deployment
metadata:
  name: composition-service
  labels:
    tier: critical
spec:
  replicas: 3
  selector:
    matchLabels:
      app: composition-service
  template:
    metadata:
      labels:
        app: composition-service
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "capability/spot"
                operator: In
                values: ["false"]
      containers:
      - name: node-app
        image: composition-service:latest
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
